GET http://localhost:8080/get_messages
Accept: text/json

###
POST http://localhost:8080/add_message
Content-Type: application/json

{
  "message": "msg10"
}

### Wrong data type. Will FAIL!
POST http://localhost:8080/add_message
Content-Type: application/json

{
  "message": {
    "some": "text"
  }
}

###
GET http://localhost:8080/get_messages
Accept: text/json

###
